name: GitHub Actions 
on: [push]
jobs: 
  init:
    runs-on: ubuntu-latest
    steps:
      - name: build app
        run: npm run build
      - name: unit testing
        run: npm run test
      - name: eslint
        run: npm run eslint
       